export default {
  allergen_classes: '',
  allergens: '',
  app_image_url: null,
  calories: 'n/a',
  category_id: 1040,
  delivery_days: null,
  description: 'Non-GMO basmati and wild rice blend topped with chicken kabob, fresh vegetables, tomato & cucumber, hummus, and roasted red pepper sauce',
  display_options: 0,
  end_date: null,
  height: null,
  id: 18369,
  ingredients: '',
  kds_groups: [],
  large_image_url: null,
  length: null,
  menu_position: 1,
  min_quantity: 1,
  name: 'Best Plate Ever',
  nutritional_info: {},
  option_groups: [
    {
      description: '',
      id: 1220,
      included_options: 0,
      is_size: 0,
      max_options: 1,
      menu_position: 1,
      min_options: 1,
      name: 'Choose Base',
      option_items: [
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1220,
          height: null,
          id: 19786,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 1,
          name: 'Rice Plate',
          nutritional_info: {},
          opt_is_default: 1,
          plu: '',
          price: '1.30',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Rice Plate',
          shorthand: '',
          slug: 'rice-plate',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1220,
          height: null,
          id: 19787,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 2,
          name: 'Salad',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '1.50',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Salad',
          shorthand: '',
          slug: 'salad',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1220,
          height: null,
          id: 19788,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 3,
          name: 'Laffa Wrap',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Laffa Wrap',
          shorthand: '',
          slug: 'laffa-wrap',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1220,
          height: null,
          id: 19789,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 4,
          name: 'Pita Sandwich',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Pita Sandwich',
          shorthand: '',
          slug: 'pita-sandwich',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
      ],
      short_name: 'Signature - Base',
      slug: 'choose-base',
    },
    {
      description: '',
      id: 1219,
      included_options: 0,
      is_size: 0,
      max_options: 2,
      menu_position: 2,
      min_options: 1,
      name: 'Choose Protein',
      option_items: [
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19779,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 1,
          name: 'Chicken Roti',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '2.50',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Chicken Roti',
          shorthand: '',
          slug: 'chicken-roti',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19780,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 2,
          name: 'Chicken Kabob',
          nutritional_info: {},
          opt_is_default: 1,
          plu: '',
          price: '2.50',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Chicken Kabob',
          shorthand: '',
          slug: 'chicken-kabob',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19781,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 3,
          name: 'Steak Roti',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '4.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Steak Roti',
          shorthand: '',
          slug: 'steak-roti',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19782,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 4,
          name: 'Salmon Kabob',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '4.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Salmon Kabob',
          shorthand: '',
          slug: 'salmon-kabob',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19783,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 5,
          name: 'Spicy Lamb Meatballs',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '4.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Spicy Lamb Meatballs',
          shorthand: '',
          slug: 'spicy-lamb-meatballs',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19784,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 6,
          name: 'Falafel',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '2.50',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Falafel',
          shorthand: '',
          slug: 'falafel',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1219,
          height: null,
          id: 19785,
          ingredients: null,
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 7,
          name: 'Vegetable',
          nutritional_info: {},
          opt_is_default: 0,
          plu: '',
          price: '2.50',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Vegetable',
          shorthand: '',
          slug: 'vegetable',
          small_image_url: null,
          start_date: null,
          tag_classes: '',
          tags: '',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
      ],
      short_name: 'Signature - Protein',
      slug: 'choose-protein',
    },
    {
      description: 'Choose as many sides as youd like',
      id: 1092,
      included_options: 0,
      is_size: 0,
      max_options: 0,
      menu_position: 3,
      min_options: 0,
      name: 'Choose Sides',
      option_items: [
        {
          allergen_classes: 'allergen-soybean-oil allergen-cilantro--coriander allergen-garlic',
          allergens: 'soybean oil, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Non-GMO basmati and wild rice blend from Lundberg Farms in California',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18347,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 1,
          name: 'Roti Rice',
          nutritional_info: {
            calories: 201,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 3,
            saturated_fat: 0,
            serving_size: 5,
            sodium: 457,
            sugars: 0,
            total_carbs: 37,
            total_fat: 4,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Basmati and wild rice blend',
          short_name: 'Roti Rice',
          shorthand: '',
          slug: 'roti-rice',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854788_800x800-rice-side.png',
          start_date: null,
          tag_classes: 'tag-roasted tag-hearty',
          tags: 'roasted, hearty',
          temperature: 'Hot',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-garlic allergen-sesame',
          allergens: 'garlic, sesame',
          app_image_url: null,
          delivery_days: null,
          description: 'Creamy hummus made from organic chickpeas with house-baked pita chips ',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18348,
          ingredients: '',
          kds_groups: [],
          large_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1501611325_hummus-white.jpg',
          length: null,
          menu_position: 2,
          name: 'Hummus',
          nutritional_info: {
            calories: 107,
            cholesterol: 0,
            dietary_fiber: 2,
            protein: 4,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 261,
            sugars: 1,
            total_carbs: 11,
            total_fat: 5,
            trans_fat: 0,
          },
          opt_is_default: 1,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Hummus made from organic chickpeas',
          short_name: 'Hummus',
          shorthand: '',
          slug: 'hummus',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854805_800x800-hummus-side.png',
          start_date: null,
          tag_classes: 'tag-tangy tag-creamy',
          tags: 'tangy, creamy',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil allergen-garlic',
          allergens: 'soybean oil, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Our take on the classic “Jerusalem Salad”.  Fresh tomatoes and cucumbers diced and tossed in olive oil and lemon juice',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18349,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 3,
          name: 'Tomato & Cucumber',
          nutritional_info: {
            calories: 19,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 148,
            sugars: 1,
            total_carbs: 2,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 1,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Fresh tomatoes and cucumbers ',
          short_name: 'Tomato & Cucumber',
          shorthand: '',
          slug: 'tomato-and-cucumber',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854816_800x800-tomcuc-side.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-tangy tag-light tag-crisp',
          tags: 'fresh, tangy, light, crisp',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil',
          allergens: 'soybean oil',
          app_image_url: null,
          delivery_days: null,
          description: 'Red cabbage, carrots and parsley tossed in our Roti Vinaigrette',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18350,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 4,
          name: 'Red Cabbage Slaw',
          nutritional_info: {
            calories: 55,
            cholesterol: 0,
            dietary_fiber: 1,
            protein: 0,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 129,
            sugars: 2,
            total_carbs: 5,
            total_fat: 3,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Red cabbage, carrots and parsley',
          short_name: 'Red Cabbage Slaw',
          shorthand: '',
          slug: 'red-cabbage-slaw',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854826_800x800-redcabbage-side.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-tangy tag-light tag-crisp',
          tags: 'fresh, tangy, light, crisp',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-gluten allergen-soybean-oil allergen-cilantro--coriander allergen-garlic',
          allergens: 'gluten, soybean oil, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'A modern take on a traditional staple of North African cuisine. Our Cous Cous is pearl shaped pasta seasoned with saffron, garlic and cumin tossed with currants \\u0003and parsley',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18351,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 5,
          name: 'Cous Cous',
          nutritional_info: {
            calories: 89,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 2,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 151,
            sugars: 1,
            total_carbs: 16,
            total_fat: 1,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Pearl shaped pasta seasoned with saffron, garlic and cumin tossed with currants \\u0003and parsley',
          short_name: 'Cous Cous',
          shorthand: '',
          slug: 'cous-cous',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854841_800x800-couscous-side.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-light',
          tags: 'fresh, light',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil allergen-garlic',
          allergens: 'soybean oil, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Our seasonal fresh vegetable are lightly seasoned, drizzled with olive oil and roasted in house',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18352,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 6,
          name: 'Fresh Vegetables',
          nutritional_info: {
            calories: 45,
            cholesterol: 0,
            dietary_fiber: 1,
            protein: 0,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 94,
            sugars: 2,
            total_carbs: 4,
            total_fat: 2,
            trans_fat: 0,
          },
          opt_is_default: 1,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Our seasonal fresh vegetables',
          short_name: 'Fresh Vegetables',
          shorthand: '',
          slug: 'fresh-vegetables',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854851_800x800-veggie-side.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-roasted tag-light',
          tags: 'fresh, roasted, light',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: 'Fresh spring mix and romaine blend',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 18353,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 7,
          name: 'Mixed Greens',
          nutritional_info: {
            calories: 10,
            cholesterol: 0,
            dietary_fiber: 1,
            protein: 0,
            saturated_fat: 0,
            serving_size: 2.25,
            sodium: 7,
            sugars: 0,
            total_carbs: 2,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Fresh spring mix and romaine blend',
          short_name: 'Mixed Greens',
          shorthand: '',
          slug: 'mixed-greens',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854868_800x800-mixedgreens-side.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-light tag-crisp',
          tags: 'fresh, light, crisp',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil allergen-cilantro--coriander allergen-garlic',
          allergens: 'soybean oil, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: '',
          end_date: null,
          group_id: 1092,
          height: null,
          id: 19448,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 8,
          name: 'Roasted Eggplant Salad',
          nutritional_info: {
            calories: 38,
            cholesterol: 0,
            dietary_fiber: 1,
            protein: 0,
            saturated_fat: 0,
            serving_size: 2,
            sodium: 237,
            sugars: 2,
            total_carbs: 4,
            total_fat: 2,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Roasted Eggplant Salad',
          shorthand: '',
          slug: 'roasted-eggplant-salad',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854885_800x800-eggplant-side.png',
          start_date: null,
          tag_classes: 'tag-charred tag-roasted tag-hearty',
          tags: 'charred, roasted, hearty',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
      ],
      short_name: 'BYO Sides',
      slug: 'choose-sides',
    },
    {
      description: 'Choose as many toppings as youd like',
      id: 1093,
      included_options: 0,
      is_size: 0,
      max_options: 0,
      menu_position: 4,
      min_options: 0,
      name: 'Choose Toppings',
      option_items: [
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: 'Kalamata olive mix',
          end_date: null,
          group_id: 1093,
          height: null,
          id: 18355,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 1,
          name: 'Kalamata Olives',
          nutritional_info: {
            calories: 84,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 1.1,
            sodium: 719,
            sugars: 0,
            total_carbs: 2,
            total_fat: 7,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Kalamata olive mix',
          short_name: 'Kalamata Olives',
          shorthand: '',
          slug: 'kalamata-olives',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854934_800x800-olives-topping.png',
          start_date: null,
          tag_classes: 'tag-tangy',
          tags: 'tangy',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-dairy',
          allergens: 'dairy',
          app_image_url: null,
          delivery_days: null,
          description: 'Crumbled feta from the Bulhozer Family, fourth generation master cheese makers from Monroe, Wisconsin',
          end_date: null,
          group_id: 1093,
          height: null,
          id: 18356,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 2,
          name: 'Feta Cheese',
          nutritional_info: {
            calories: 82,
            cholesterol: 27,
            dietary_fiber: 0,
            protein: 4,
            saturated_fat: 4,
            serving_size: 1.1,
            sodium: 348,
            sugars: 1,
            total_carbs: 1,
            total_fat: 6,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Crumbled feta cheese',
          short_name: 'Feta Cheese',
          shorthand: '',
          slug: 'feta-cheese',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854942_800x800-feta-topping.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-tangy tag-creamy',
          tags: 'fresh, tangy, creamy',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: 'Cucumber pickles made with lemon and fresh oregano',
          end_date: null,
          group_id: 1093,
          height: null,
          id: 18357,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 3,
          name: 'Lemon Oregano Pickles',
          nutritional_info: {
            calories: 5,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 1,
            sodium: 380,
            sugars: 1,
            total_carbs: 1,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Pickles made with lemon and fresh oregano',
          short_name: 'Lemon Oregano Pickles',
          shorthand: '',
          slug: 'lemon-oregano-pickles',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854949_800x800-pickles-topping.png',
          start_date: null,
          tag_classes: 'tag-tangy tag-crisp',
          tags: 'tangy, crisp',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: '',
          allergens: '',
          app_image_url: null,
          delivery_days: null,
          description: 'House-pickled red onions',
          end_date: null,
          group_id: 1093,
          height: null,
          id: 18358,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 4,
          name: 'Pickled Onions',
          nutritional_info: {
            calories: 48,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 1.1,
            sodium: 208,
            sugars: 8,
            total_carbs: 10,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'House-pickled red onions',
          short_name: 'Pickled Onions',
          shorthand: '',
          slug: 'pickled-onions',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854958_800x800-pickledonions-topping.png',
          start_date: null,
          tag_classes: 'tag-tangy tag-crisp',
          tags: 'tangy, crisp',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-cilantro--coriander',
          allergens: 'cilantro / coriander',
          app_image_url: null,
          delivery_days: null,
          description: 'Fresh chopped cilantro',
          end_date: null,
          group_id: 1093,
          height: null,
          id: 18359,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 5,
          name: 'Chopped Cilantro',
          nutritional_info: {
            calories: 0,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 0.15,
            sodium: 1,
            sugars: 0,
            total_carbs: 0,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Fresh chopped cilantro',
          short_name: 'Chopped Cilantro',
          shorthand: '',
          slug: 'chopped-cilantro',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854969_800x800-cilantro-topping.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-light',
          tags: 'fresh, light',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
      ],
      short_name: 'BYO Toppings',
      slug: 'choose-toppings',
    },
    {
      description: 'Choose your sauces',
      id: 1094,
      included_options: 0,
      is_size: 0,
      max_options: 0,
      menu_position: 5,
      min_options: 0,
      name: 'Choose Sauce',
      option_items: [
        {
          allergen_classes: 'allergen-dairy allergen-garlic',
          allergens: 'dairy, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Our take on a traditional Tzatziki. We use low fat Greek yogurt, sprinkled with dill, for a creamy, but not too heavy, sauce',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18360,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 1,
          name: 'Dill, Yogurt & Cucumber (mild)',
          nutritional_info: {
            calories: 25,
            cholesterol: 1,
            dietary_fiber: 0,
            protein: 2,
            saturated_fat: 0,
            serving_size: 1,
            sodium: 51,
            sugars: 0,
            total_carbs: 1,
            total_fat: 1,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Our take on a traditional Tzatziki',
          short_name: 'Dill, Yogurt & Cucumber',
          shorthand: '',
          slug: 'dill-yogurt-and-cucumber-mild',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854693_800x800-dillcuc-sauce.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-tangy tag-creamy tag-light',
          tags: 'fresh, tangy, creamy, light',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-dairy allergen-soybean-oil allergen-eggs allergen-garlic',
          allergens: 'dairy, soybean oil, eggs, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Garlic sauce with lemon juice, sea salt and black pepper',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18361,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 2,
          name: 'Garlic (mild)',
          nutritional_info: {
            calories: 111,
            cholesterol: 10,
            dietary_fiber: 0,
            protein: 1,
            saturated_fat: 2,
            serving_size: 1,
            sodium: 150,
            sugars: 1,
            total_carbs: 11,
            total_fat: 11,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Garlic sauce with lemon juice, sea salt and black pepper',
          short_name: 'Garlic',
          shorthand: '',
          slug: 'garlic-mild',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854703_800x800-garlic-sauce.png',
          start_date: null,
          tag_classes: 'tag-creamy',
          tags: 'creamy',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-garlic allergen-sesame',
          allergens: 'garlic, sesame',
          app_image_url: null,
          delivery_days: null,
          description: 'A traditional Mediterranean favorite. Made from sesame seed paste',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18362,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 3,
          name: 'Tahini (mild)',
          nutritional_info: {
            calories: 74,
            cholesterol: 0,
            dietary_fiber: 1,
            protein: 2,
            saturated_fat: 1,
            serving_size: 1,
            sodium: 62,
            sugars: 0,
            total_carbs: 2,
            total_fat: 6,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'A traditional Mediterranean favorite. Made from sesame seed paste',
          short_name: 'Tahini',
          shorthand: '',
          slug: 'tahini-mild',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854713_800x800-tahini-sauce.png',
          start_date: null,
          tag_classes: 'tag-creamy tag-roasted',
          tags: 'creamy, roasted',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-honey allergen-soybean-oil',
          allergens: 'honey, soybean oil',
          app_image_url: null,
          delivery_days: null,
          description: 'House recipe made with red wine vinaigrette, honey, and seasonings ',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18363,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 4,
          name: 'Red Wine Vinaigrette (mild)',
          nutritional_info: {
            calories: 135,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 1,
            serving_size: 1,
            sodium: 172,
            sugars: 5,
            total_carbs: 5,
            total_fat: 12,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'House recipe made with red wine vinaigrette, honey, and seasonings ',
          short_name: 'Red Wine Vinaigrette',
          shorthand: '',
          slug: 'red-wine-vinaigrette-mild',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854724_800x800-redvin-sauce.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-tangy tag-light',
          tags: 'fresh, tangy, light',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil allergen-cilantro--coriander allergen-garlic',
          allergens: 'soybean oil, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'Spicy sauce made with fresh herbs, lemon, garlic, and jalapeno ',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18364,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 5,
          name: 'Green Shug (spicy)',
          nutritional_info: {
            calories: 74,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 1,
            serving_size: 1,
            sodium: 180,
            sugars: 0,
            total_carbs: 2,
            total_fat: 7,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Spicy sauce made with fresh herbs, lemon, garlic, and jalapeno ',
          short_name: 'Green Shug',
          shorthand: '',
          slug: 'green-shug-spicy',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854733_800x800-greenshug-sauce.png',
          start_date: null,
          tag_classes: 'tag-fresh tag-spicy',
          tags: 'fresh, spicy',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-soybean-oil allergen-cilantro--coriander allergen-garlic',
          allergens: 'soybean oil, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'S’hug (shoog) is a popular condiment in the Eastern Mediterranean. Made with crushed red pepper, fresh garlic, and cayenne pepper',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 18365,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 6,
          name: 'Red Shug (spicy)',
          nutritional_info: {
            calories: 33,
            cholesterol: 0,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 1,
            sodium: 147,
            sugars: 4,
            total_carbs: 6,
            total_fat: 0,
            trans_fat: 0,
          },
          opt_is_default: 0,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: 'Made with crushed red pepper, fresh garlic, and cayenne pepper',
          short_name: 'Red Shug',
          shorthand: '',
          slug: 'red-shug-spicy',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854759_800x800-redshug-sauce.png',
          start_date: null,
          tag_classes: 'tag-spicy tag-rich',
          tags: 'spicy, rich',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
        {
          allergen_classes: 'allergen-dairy allergen-soybean-oil allergen-eggs allergen-cilantro--coriander allergen-garlic',
          allergens: 'dairy, soybean oil, eggs, cilantro / coriander, garlic',
          app_image_url: null,
          delivery_days: null,
          description: 'A customer favorite, this sauce is beautiful and delicious. Roasted red peppers, capers, and garlic enliven this medium spicy sauce.',
          end_date: null,
          group_id: 1094,
          height: null,
          id: 19447,
          ingredients: '',
          kds_groups: [],
          large_image_url: null,
          length: null,
          menu_position: 7,
          name: 'Roasted Red Pepper (medium)',
          nutritional_info: {
            calories: 117,
            cholesterol: 11,
            dietary_fiber: 0,
            protein: 0,
            saturated_fat: 0,
            serving_size: 1,
            sodium: 92,
            sugars: 0,
            total_carbs: 1,
            total_fat: 12,
            trans_fat: 0,
          },
          opt_is_default: 1,
          plu: '',
          price: '0.00',
          sales_tax_override: null,
          service_restrictions: null,
          serving_size: null,
          short_description: '',
          short_name: 'Roasted Red Pepper',
          shorthand: '',
          slug: 'roasted-red-pepper-medium',
          small_image_url: '//s3.amazonaws.com/betterboh/u/img/prod/46/1508854767_800x800-redpepper-sauce.png',
          start_date: null,
          tag_classes: 'tag-tangy tag-creamy tag-roasted',
          tags: 'tangy, creamy, roasted',
          temperature: 'Cold',
          weight: null,
          width: null,
        },
      ],
      short_name: 'BYO Sauce',
      slug: 'choose-sauce',
    },
  ],
  plu: '',
  price: '4.45',
  sales_tax_override: null,
  service_restrictions: null,
  short_description: '',
  short_name: 'Best Plate Ever',
  shorthand: '',
  sizes: [],
  slug: 'best-plate-ever',
  small_image_url: null,
  start_date: null,
  tag_classes: '',
  tags: '',
  temperature: 'Cold',
  use_options_wizard: 1,
  weight: null,
  width: null,
};
